export interface AkababRsI{
    id: number;
    name: string,
    height: number,
    mass: number,
    gender: string,
    homeworld: string,
    species: string,
    wiki: string,
    image: string,
    dateCreated: number,
    dateDestroyed: number,
    destroyedLocation: string,
    creator: string,
    manufacturer: string,
    model: string,
    class: string,
    sensorColor: string,
    platingColor: string,
    died: number,
    equipment: string,
    affiliations: [],
    skinColor: string,
    eyeColor: string,
    born: number,
    masters: [],
    apprentices: [],
    formerAffiliations:[]
}